.TH MASTERCP 1
.SH NAME
mastercp \- Controls all the programs masterfully
.SH SYNOPSIS
\fBmastercp\fR
.SH EXIT STATUS
.TP
\fB0\fR
Successful program execution.

.TP
\fB1\fR
Unsuccessful program execution.

.TP
\fB101\fR
The program panicked.
.SH AUTHORS
.P
.RS 2
.nf
Michael Sarfati <msarfati@protonmail.com>
Jane Smith <jsmith@somemail.com>
Alice Person <alice@person.com>
Bob Human <bob@human.com>
